// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmLF-dio4Hgj-Z8dx6HQdpFTJYNuwKAlM',
    appId: '1:644059812778:web:33820a53eb7d708f2191d3',
    messagingSenderId: '644059812778',
    projectId: 'sprinkelcell-notes',
    authDomain: 'sprinkelcell-notes.firebaseapp.com',
    storageBucket: 'sprinkelcell-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ5X8lNJCkp426nQ9-hnVd4S0WfjqQY9Y',
    appId: '1:644059812778:android:434b6b5b348f64952191d3',
    messagingSenderId: '644059812778',
    projectId: 'sprinkelcell-notes',
    storageBucket: 'sprinkelcell-notes.appspot.com',
  );
}
